### ISSUE TITLE
Form not working with nested resource

### ISSUE THREAD

**Issue by BenjaminDigeon** [richardvenneman/trestle-active_storage#2]
With a simple has_one nested resource, the form it's not working.

For example :

```ruby
class User < ApplicationRecord
  has_one :user_profile, dependent: :destroy
end
```
```ruby
class UserProfile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end
```
```ruby
Trestle.resource(:users) do
  active_storage_fields do
    [:avatar]
  end
  form do |user|
    fields_for :user_profile do
      active_storage_field :avatar
    end
  end
end
```

With no avatar attached, when trying to upload a avatar i get a 404 :

```
ActiveRecord::RecordNotFound (Couldn't find UserProfile with ID=8f3d1edf-1029-4464-8cc1-470d3de2d6af for User with ID=):

activerecord (5.2.0) lib/active_record/nested_attributes.rb:596:in `raise_nested_attributes_record_not_found!'
activerecord (5.2.0) lib/active_record/nested_attributes.rb:420:in `assign_nested_attributes_for_one_to_one_association'
activerecord (5.2.0) lib/active_record/nested_attributes.rb:373:in `user_profile_attributes='
activemodel (5.2.0) lib/active_model/attribute_assignment.rb:51:in `public_send'
activemodel (5.2.0) lib/active_model/attribute_assignment.rb:51:in `_assign_attribute'
activerecord (5.2.0) lib/active_record/attribute_assignment.rb:31:in `block in assign_nested_parameter_attributes'
activerecord (5.2.0) lib/active_record/attribute_assignment.rb:31:in `each'
activerecord (5.2.0) lib/active_record/attribute_assignment.rb:31:in `assign_nested_parameter_attributes'
activerecord (5.2.0) lib/active_record/attribute_assignment.rb:25:in `_assign_attributes'
activemodel (5.2.0) lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
activerecord (5.2.0) lib/active_record/core.rb:314:in `initialize'
activerecord (5.2.0) lib/active_record/inheritance.rb:66:in `new'
activerecord (5.2.0) lib/active_record/inheritance.rb:66:in `new'
trestle (0.8.9) lib/trestle/adapters/active_record_adapter.rb:13:in `build_instance'
trestle (0.8.9) lib/trestle/resource.rb:36:in `public_send'
trestle (0.8.9) lib/trestle/resource.rb:36:in `block in adapter_method'
trestle-active_storage (0.0.1.pre.12) lib/trestle/active_storage/controller_concern.rb:28:in `attach_attachments'
activesupport (5.2.0) lib/active_support/callbacks.rb:426:in `block in make_lambda'
activesupport (5.2.0) lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
actionpack (5.2.0) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (5.2.0) lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
activesupport (5.2.0) lib/active_support/callbacks.rb:513:in `block in invoke_before'
activesupport (5.2.0) lib/active_support/callbacks.rb:513:in `each'
activesupport (5.2.0) lib/active_support/callbacks.rb:513:in `invoke_before'
activesupport (5.2.0) lib/active_support/callbacks.rb:107:in `block in run_callbacks'
activesupport (5.2.0) lib/active_support/callbacks.rb:136:in `run_callbacks'
actionpack (5.2.0) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.0) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.0) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.0) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.0) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.0) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.0) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.0) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.0) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.0) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.0) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
railties (5.2.0) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.0) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.0) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.0) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:840:in `call'
rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
actionpack (5.2.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.0) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.0) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

And with a avatar already attached i get a error when building the form : 

```
ActionView::Template::Error (undefined method `delete_avatar' for #<UserProfile:0x00007fcc0f954380>):
     9:       <% end %>
    10:     </div>
    11:
    12:     <%= builder.check_box("delete_#{field_name}", label: "Delete #{field_name}") %>
    13:   <% end %>
    14:
    15:   <div class="progress" style="display: none">
```

**Comment by staroflead** [comment]
(Couldn't find UserProfile with ID=8f3d1edf-1029-4464-8cc1-470d3de2d6af for User with ID=)
I think it doesn't gem fault. Pls check your code at this block
```
form do |user|
    fields_for :user_profile do
      active_storage_field :avatar
    end
end
```
I think you should change it to
```
form do |user|
    fields_for user.user_profile do |profile|
      active_storage_field profile.avatar
    end
 end
```

**Comment by richardvenneman** [comment]
Closing due to @staroflead's solution and inactivity. If this is still an issue feel free to comment.

**Comment by K4sku** [comment]
This does not work because `ControllerConcern.define_attachment_accessors` does not create accessors and `"delete_#{field}"` methods for nested attachments. 

I think there should be a way to define `active_storage_fields` as hash, in this case, something like this:

```ruby
active_storage_fields do 
  [:some_user_attachment, profile: [:avatar]]
end
```

And then the `purge_attachments` method would need to be aware of this.
